name       : qownnotes
version    : 17.10.7
release    : 85
source     :
    - https://freefr.dl.sourceforge.net/project/qownnotes/src/qownnotes-17.10.7.tar.xz : 8cd6ee1c487fb5ec7b96df32383719cdfea29f75f97157f4333a95fb95479180
license    : GPL-2.0
homepage   : http://www.qownnotes.org
component  : office.notes
summary    : QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
description: |
    QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
rundeps    :
    - qt5-svg
setup      : |
    echo "#define RELEASE \"Solus\"" > release.h
build      : |
    %qmake
    %make
install    : |
    install -Dm00755 QOwnNotes $installdir/usr/bin/QOwnNotes
    install -Dm00644 QOwnNotes.desktop $installdir/usr/share/applications/QOwnNotes.desktop
    for size in {16x16,24x24,32x32,48x48,64x64,96x96,128x128,256x256,512x512}; do
        install -Dm00644 images/icons/$size/apps/QOwnNotes.png $installdir/usr/share/icons/hicolor/$size/apps/QOwnNotes.png
    done
    install -Dm00644 images/icons/scalable/apps/QOwnNotes.svg $installdir/usr/share/icons/hicolor/scalable/apps/QOwnNotes.svg
    install -dm00644 $installdir/usr/share/QOwnNotes/languages/
    install -Dm00644 languages/*.qm $installdir/usr/share/QOwnNotes/languages/
