name       : qownnotes
version    : 18.04.3
release    : 118
source     :
    - https://download.tuxfamily.org/qownnotes/src/qownnotes-18.04.3.tar.xz : ccb6b154434af566f0fff98828f2f1a34130beee4ded754bc4f9af6ab6ac926c
license    : GPL-2.0
homepage   : http://www.qownnotes.org
component  : office.notes
summary    : QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
description: |
    QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
rundeps    :
    - qt5-svg
setup      : |
    echo "#define RELEASE \"Solus\"" > release.h
build      : |
    %qmake
    %make
install    : |
    install -Dm00755 QOwnNotes $installdir/usr/bin/QOwnNotes
    install -Dm00644 QOwnNotes.desktop $installdir/usr/share/applications/QOwnNotes.desktop
    for size in {16x16,24x24,32x32,48x48,64x64,96x96,128x128,256x256,512x512}; do
        install -Dm00644 images/icons/$size/apps/QOwnNotes.png $installdir/usr/share/icons/hicolor/$size/apps/QOwnNotes.png
    done
    install -Dm00644 images/icons/scalable/apps/QOwnNotes.svg $installdir/usr/share/icons/hicolor/scalable/apps/QOwnNotes.svg
    install -dm00644 $installdir/usr/share/QOwnNotes/languages/
    install -Dm00644 languages/*.qm $installdir/usr/share/QOwnNotes/languages/
