name       : qownnotes
version    : 19.10.4
release    : 202
source     :
    - https://download.tuxfamily.org/qownnotes/src/qownnotes-19.10.4.tar.xz : b4bf064be0a8ca7ed416b0338d5ae0b1c6b736207dde9d438d60cdf75c2bd152
license    : GPL-2.0
homepage   : http://www.qownnotes.org
component  : office.notes
summary    : QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
description: |
    QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5XmlPatterns)
rundeps    :
    - qt5-svg
setup      : |
    echo "#define RELEASE \"Solus\"" > release.h
build      : |
    %qmake
    %make
install    : |
    install -Dm00755 QOwnNotes $installdir/usr/bin/QOwnNotes
    # Keep this as QOwnNotes. Breaks Budgie otherwise.
    install -Dm00644 PBE.QOwnNotes.desktop $installdir/usr/share/applications/QOwnNotes.desktop
    for size in {16x16,24x24,32x32,48x48,64x64,96x96,128x128,256x256,512x512}; do
        install -Dm00644 images/icons/$size/apps/QOwnNotes.png $installdir/usr/share/icons/hicolor/$size/apps/QOwnNotes.png
    done
    install -Dm00644 images/icons/scalable/apps/QOwnNotes.svg $installdir/usr/share/icons/hicolor/scalable/apps/QOwnNotes.svg
    install -dm00644 $installdir/usr/share/QOwnNotes/languages/
    install -Dm00644 languages/*.qm $installdir/usr/share/QOwnNotes/languages/
