name       : qownnotes
version    : 21.11.7
release    : 286
source     :
    - https://download.tuxfamily.org/qownnotes/src/qownnotes-21.11.7.tar.xz : 17ebe5feb0d0e08466d3551dce826f1b0c02a76178c60f8dfa5b64af763bdd97
license    : GPL-2.0-or-later
homepage   : http://www.qownnotes.org
component  : office.notes
summary    : QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
description: |
    QOwnNotes is a plain-text file notepad and todo-list manager with markdown support and ownCloud integration.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(x11)
rundeps    :
    - qt5-svg
setup      : |
    echo "#define RELEASE \"Solus\"" > release.h
    %patch -p2 < $pkgfiles/0001-Patch-out-Update-Available-button.patch
build      : |
    %qmake
    %make
install    : |
    install -Dm00755 QOwnNotes $installdir/usr/bin/QOwnNotes
    # Keep this as QOwnNotes. Breaks Budgie otherwise.
    install -Dm00644 PBE.QOwnNotes.desktop $installdir/usr/share/applications/QOwnNotes.desktop
    for size in {16x16,24x24,32x32,48x48,64x64,96x96,128x128,256x256,512x512}; do
        install -Dm00644 images/icons/$size/apps/QOwnNotes.png $installdir/usr/share/icons/hicolor/$size/apps/QOwnNotes.png
    done
    install -Dm00644 images/icons/scalable/apps/QOwnNotes.svg $installdir/usr/share/icons/hicolor/scalable/apps/QOwnNotes.svg
    install -dm00644 $installdir/usr/share/qt5/translations
    install -Dm00644 languages/*.qm $installdir/usr/share/qt5/translations
